### ISSUE TITLE
Error running on Solus 4.3

### ISSUE THREAD

**Issue by edalongeville** [andreasomaini/apex-m800-cfg#2]
Hello!

Thanks a lot for writing this piece of code.
I'm having an issue trying to run it on Solus 4.3. Here's what I get:
```
eric@desktop ~/Git $ cd apex-m800-cfg/
eric@desktop ~/Git/apex-m800-cfg $ ./uploader configurations/configuration1
./uploader: Error during device opening
eric@desktop ~/Git/apex-m800-cfg $ sudo ./uploader configurations/configuration1
./uploader: Unable to send payload n.0: Resource temporarily unavailable
```

Here's what my lsusb returns:
```
lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 004: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0
Bus 005 Device 003: ID 1038:1600 SteelSeries ApS SteelSeries Apex M800 Keyboard
Bus 005 Device 002: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 004: ID 2833:0211 Oculus VR, Inc. Rift CV1 Sensor
Bus 004 Device 003: ID 2109:0812 VIA Labs, Inc. VL812 Hub
Bus 004 Device 002: ID 2833:0211 Oculus VR, Inc. Rift CV1 Sensor
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 2109:2812 VIA Labs, Inc. VL812 Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1038:1250 SteelSeries ApS SteelSeries Arctis 5
Bus 001 Device 002: ID 1038:184c SteelSeries ApS SteelSeries Rival 3
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Could you please help me troubleshoot this ?

Thanks!

**Comment by thegoldgoat** [comment]
Hello,

I don’t have that keyboard anymore. However, I can say this is the line where the problem relies: https://github.com/andreasomaini/apex-m800-cfg/blob/88e0c74fbe3561be639e09787991d9aad3a58379/src/uploader/main.c#L82

you should check the value of `bytesSent` just after that call. Here is what that function does, according to documentation:

> Perform a USB control transfer. Returns the actual number of bytes transferred on success, in the range from and including zero up to and including wLength. On error a LIBUSB_ERROR code is returned, for example LIBUSB_ERROR_TIMEOUT if the transfer timed out, LIBUSB_ERROR_PIPE if the control request was not supported, LIBUSB_ERROR_NO_DEVICE if the device has been disconnected and another LIBUSB_ERROR code on other failures. The LIBUSB_ERROR codes are all negative.

check which of these LIBUSB_ERROR_* `bytesSent` is.

My guess is that you have some other software that connects to the keyboard and keeps it busy (?)

**Comment by edalongeville** [comment]
Thanks a lot!
I did not even get the chance to troubleshoot this, I tried again after updating my system and it worked. I'm now able to load a profile.

Again, thank you for writing this tool.
